name: pawscare
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  provider: ^6.0.5
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  image_picker: ^1.0.4
  share_plus: ^7.2.1
  cached_network_image: ^3.3.0
  http: ^1.2.1
  path_provider: ^2.1.3
  photo_view: ^0.14.0
  smooth_page_indicator: ^1.2.1
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.3.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^17.2.3
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  google_places_flutter: ^2.0.9
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  # glass_kit: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/welcome1.png
    - assets/images/welcome2.png
    - assets/images/welcome3.png
    - assets/images/welcome4.png
    - assets/images/welcome5.png
    - assets/images/pawscarelogo.svg   # ✅ added SVG logo
    - lib/assets/pawscare_logo.png     # ✅ kept your existing logo
    - assets/.env                       # ✅ Environment variables

  fonts:
    - family: Borel
      fonts:
        - asset: assets/fonts/Borel-Regular.ttf   # ✅ added your font
